server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    pl.studyshare: INFO